version: "2.0"
services:

    bibbox-molgenis:
      image: registry.molgenis.org/molgenis/molgenis-app:latest
      container_name: bibbox-molgenis
      environment:
        - molgenis.home=/home/molgenis
        - python_script_executable=/usr/bin/python3
        - opencpu.uri.host=opencpu
        - elasticsearch.transport.addresses=elasticsearch:9300
        - db_uri=jdbc:postgresql://postgres/molgenis
        - db_user=molgenis
        - db_password=molgenis
        - admin.password=admin
        - MINIO_BUCKET_NAME=molgenis
        - MINIO_ENDPOINT=http://minio:9000
        - MINIO_ACCESS_KEY=molgenis
        - MINIO_SECRET_KEY=molgenis
        - "CATALINA_OPTS=-Xmx1g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
      ports:
        - "8081:8080"
      links:
        - bibbox-molgenis-postgres:postgres
        - bibbox-molgenis-minio:minio
        - bibbox-molgenis-elasticsearch:elasticsearch
        - bibbox-molgenis-opencpu:opencpu
      volumes_from: 
        - bibbox-molgenis-data
      depends_on:
        - bibbox-molgenis-postgres


    bibbox-molgenis-frontend:
      container_name: bibbox-molgenis-frontend
      image: molgenis/molgenis-frontend:latest
      ports:
        - "82:80"
      volumes: 
        - ./backend.conf:/etc/nginx/proxy.d/backend.conf
      volumes_from: 
        - bibbox-molgenis-data
      depends_on:
        - "bibbox-molgenis"
    
    bibbox-molgenis-postgres:
      image: postgres:11-alpine
      container_name: bibbox-molgenis-postgres
      environment:
        - POSTGRES_USER=molgenis
        - POSTGRES_PASSWORD=molgenis
        - POSTGRES_DB=molgenis
      expose:
        - "5432"
      volumes_from: 
        - bibbox-molgenis-data
      command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'

    bibbox-molgenis-elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
      container_name: bibbox-molgenis-elasticsearch
      environment:
        - cluster.name=molgenis
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes_from: 
          - bibbox-molgenis-data
      ports:
        - 9200:9200
        - 9300:9300

    bibbox-molgenis-opencpu:
        image: molgenis/opencpu:opencpu-release-2019-03-20_12-07-11
        container_name: bibbox-molgenis-opencpu
        ports:
          - 8004:8004

    bibbox-molgenis-minio:
      image: minio/minio:RELEASE.2019-03-20T22-38-47Z
      container_name: bibbox-molgenis-minio
      volumes_from: 
        - bibbox-molgenis-data
      ports:
        - 9001:9001
      environment:
        MINIO_ACCESS_KEY: molgenis
        MINIO_SECRET_KEY: molgenis
      command: server /data

    bibbox-molgenis-data:
        image: busybox
        container_name: bibbox-molgenis-data
        volumes:
          - ./data/var/lib/postgresql/data:/var/lib/postgresql/data
          - ./data/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
          - ./data/home/molgenis:/home/molgenis
          - ./data/minio/data:/data
        command: chmod -R 777 /usr/share/elasticsearch/data
